import Foundation

class LLMClient {
    static let shared = LLMClient()
    private init() {}
    
    /// Returns an asynchronous stream yielding text deltas as they are generated by the chosen LLM provider.
    /// - Parameters:
    ///   - providerType: Either "anthropic" or "openai".
    ///   - history: The array of previous chat messages.
    ///   - concept: If in Feynman evaluation mode, the specific concept term.
    ///   - isFeynmanMode: Whether to trigger strict evaluation prompt instructions.
    ///   - apiKey: The user's Anthropic/OpenAI API key.
    ///   - apiURL: The base URL of the API.
    ///   - model: The model designation.
    func getResponseStream(
        providerType: String,
        history: [ChatMessage],
        concept: String?,
        isFeynmanMode: Bool,
        apiKey: String,
        apiURL: String,
        model: String
    ) -> AsyncThrowingStream<String, Error> {
        let provider = LLMProviderFactory.makeProvider(for: providerType)
        return provider.getResponseStream(
            history: history,
            concept: concept,
            isFeynmanMode: isFeynmanMode,
            apiKey: apiKey,
            apiURL: apiURL,
            model: model
        )
    }
}
